### ISSUE TITLE
laser-camera-camlib

### ISSUE THREAD

**Issue by www516717402** [XidianLemon/calibration_camera_lidar#1]
你好，我想问一下。我现在工业相机在ROS中没有驱动，启动不了，雷达在Ros中可以驱动。请问这样的情况怎么进行相机和雷达的联合标定呢？autoware可以直接输入图片和雷达的pcd文件进行联合标定吗？感谢回答

**Comment by XidianLemon** [comment]
> 你好，我想问一下。我现在工业相机在ROS中没有驱动，启动不了，雷达在Ros中可以驱动。请问这样的情况怎么进行相机和雷达的联合标定呢？autoware可以直接输入图片和雷达的pcd文件进行联合标定吗？感谢回答

autoware软件目前没有输入图片和pcd直接标定的功能。您说的这种情况可以有两个办法：
1.自己编写工业相机的ros驱动，记得话题名改成/usb_cam/image_raw。
2.从我这个包里面的calibration_camera_lidar/文件夹中找到他联合标定的代码，这些代码读懂困难，因为涉及论文里很多公式，但只要把这一段代码拿出来，然后编写读取pcd和image的程序，再让他输出yaml标定文件即可。
第一种方法简单，第二种方法会使您对autoware代码结构更清晰。希望可以帮到您。

**Comment by njauwangkai** [comment]
您好，请问16线激光雷达能够 使用autoware进行联合标定吗？您尝试过吗？会不会因为16线激光线束太少而标定不成功？感谢您的回答

**Comment by XidianLemon** [comment]
> 您好，请问16线激光雷达能够 使用autoware进行联合标定吗？您尝试过吗？会不会因为16线激光线束太少而标定不成功？感谢您的回答

当然可以用，16线和32线我都尝试过，只要选择对应位置选的准确，标定的就会准确，velodyne的雷达对标定板到雷达的距离没什么太大的要求，而有些雷达需要手动调整雷达到标定板的距离，因为有些雷达的强度方面会在某些位置看不到标定板。可能您是个GitHub的新手，下回提问记得新开一个issue，也就是右上角的new issue那个按钮。有问题欢迎探讨，这里没有蠢问题。

**Comment by www516717402** [comment]
thank you for answer views。Now，I finish the cam-laser-calib from windows by line and line method that reference to 《Extrinsic_improve_camera_calibration》

**Comment by XidianLemon** [comment]
> thank you for answer views。Now，I finish the cam-laser-calib from windows by line and line method that reference to 《Extrinsic_improve_camera_calibration》

goodluck
