### ISSUE TITLE
无法选中chessboard对应的平面

### ISSUE THREAD

**Issue by JunzWu** [XidianLemon/calibration_camera_lidar#13]
你好，想问一下我用你的程序进行标定的时候遇到了下图的情况：没有办法选中chessboard对应的平面。是因为我Lidar用的16线，过于稀疏导致选不中吗？但是我之前用原版autoware的时候是可以选中的，原版autoware我是在实验室的Ubuntu 16.04电脑上装的，你的程序是在我自己电脑ubuntu 18.04上装的。或者说有办法让这个圈变大一点吗？
![Screenshot from 2021-01-22 14-31-10](https://user-images.githubusercontent.com/46737744/105542467-02c66f00-5cbf-11eb-9a2f-8c70b3e1126c.png)

**Comment by JunzWu** [comment]
我忘记调size了。。。。

**Comment by zhangyuran-gg** [comment]
> 我忘记调size了。。。。

你好，这个圈只要打到点云中的标定板平面就可以吗，我用30帧数据做calib计算的结果差距很大
